from fastapi import APIRouter, Depends, Query
from sqlalchemy.orm import Session
from database import get_db
from models import User, Report, Incident, CAPA
from dependencies import get_current_active_user
from datetime import datetime, timedelta
import uuid
import logging
from pydantic import BaseModel
from typing import Optional, List
from sqlalchemy import func

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/reports", tags=["reports"])

# ==================== Report Schemas ====================

class ReportResponse(BaseModel):
    id: uuid.UUID
    report_number: str
    report_type: str
    title: str
    generated_date: datetime
    start_date: datetime
    end_date: datetime
    total_incidents: int
    total_capa: int
    created_at: datetime

    class Config:
        from_attributes = True

class ReportsListResponse(BaseModel):
    total: int
    page: int
    page_size: int
    pages: int
    data: List[ReportResponse]

# ==================== Routes ====================

@router.get("/", response_model=ReportsListResponse)
async def list_reports(
    page: int = Query(1, ge=1),
    page_size: int = Query(10, ge=1, le=100),
    report_type: Optional[str] = None,
    current_user: User = Depends(get_current_active_user),
    db: Session = Depends(get_db)
):
    """
    List reports with pagination and filtering
    """
    query = db.query(Report)
    
    if report_type:
        query = query.filter(Report.report_type == report_type)
    
    total = query.count()
    skip = (page - 1) * page_size
    reports = query.order_by(Report.generated_date.desc()).offset(skip).limit(page_size).all()
    
    return ReportsListResponse(
        total=total,
        page=page,
        page_size=page_size,
        pages=(total + page_size - 1) // page_size,
        data=reports
    )

@router.post("/generate-daily")
async def generate_daily_report(
    current_user: User = Depends(get_current_active_user),
    db: Session = Depends(get_db)
):
    """
    Generate daily report
    """
    today = datetime.utcnow().date()
    start_date = datetime.combine(today, datetime.min.time())
    end_date = datetime.combine(today, datetime.max.time())
    
    # Count incidents and CAPA for today
    incident_count = db.query(func.count(Incident.id)).filter(
        Incident.created_at >= start_date,
        Incident.created_at <= end_date
    ).scalar()
    
    capa_count = db.query(func.count(CAPA.id)).filter(
        CAPA.created_at >= start_date,
        CAPA.created_at <= end_date
    ).scalar()
    
    # Generate report number
    report_number = f"RPT-{today.strftime('%Y%m%d')}-DAILY"
    
    report = Report(
        report_number=report_number,
        report_type="daily",
        title=f"Daily Report - {today.strftime('%Y-%m-%d')}",
        start_date=start_date,
        end_date=end_date,
        total_incidents=incident_count,
        total_capa=capa_count,
        generated_date=datetime.utcnow(),
        created_by=current_user.id
    )
    
    db.add(report)
    db.commit()
    db.refresh(report)
    
    logger.info(f"Daily report {report_number} generated by {current_user.email}")
    
    return ReportResponse.from_orm(report)

@router.post("/generate-weekly")
async def generate_weekly_report(
    current_user: User = Depends(get_current_active_user),
    db: Session = Depends(get_db)
):
    """
    Generate weekly report
    """
    today = datetime.utcnow()
    start_date = today - timedelta(days=today.weekday())
    end_date = today
    
    # Count incidents and CAPA for the week
    incident_count = db.query(func.count(Incident.id)).filter(
        Incident.created_at >= start_date,
        Incident.created_at <= end_date
    ).scalar()
    
    capa_count = db.query(func.count(CAPA.id)).filter(
        CAPA.created_at >= start_date,
        CAPA.created_at <= end_date
    ).scalar()
    
    # Generate report number
    week_number = today.isocalendar()[1]
    report_number = f"RPT-{today.strftime('%Y')}-W{week_number:02d}"
    
    report = Report(
        report_number=report_number,
        report_type="weekly",
        title=f"Weekly Report - Week {week_number}",
        start_date=start_date,
        end_date=end_date,
        total_incidents=incident_count,
        total_capa=capa_count,
        generated_date=datetime.utcnow(),
        created_by=current_user.id
    )
    
    db.add(report)
    db.commit()
    db.refresh(report)
    
    logger.info(f"Weekly report {report_number} generated by {current_user.email}")
    
    return ReportResponse.from_orm(report)

@router.post("/generate-monthly")
async def generate_monthly_report(
    current_user: User = Depends(get_current_active_user),
    db: Session = Depends(get_db)
):
    """
    Generate monthly report
    """
    today = datetime.utcnow()
    start_date = today.replace(day=1)
    if today.month == 12:
        end_date = today.replace(year=today.year + 1, month=1, day=1) - timedelta(days=1)
    else:
        end_date = today.replace(month=today.month + 1, day=1) - timedelta(days=1)
    
    # Count incidents and CAPA for the month
    incident_count = db.query(func.count(Incident.id)).filter(
        Incident.created_at >= start_date,
        Incident.created_at <= end_date
    ).scalar()
    
    capa_count = db.query(func.count(CAPA.id)).filter(
        CAPA.created_at >= start_date,
        CAPA.created_at <= end_date
    ).scalar()
    
    # Generate report number
    report_number = f"RPT-{today.strftime('%Y%m')}-MONTHLY"
    
    report = Report(
        report_number=report_number,
        report_type="monthly",
        title=f"Monthly Report - {today.strftime('%B %Y')}",
        start_date=start_date,
        end_date=end_date,
        total_incidents=incident_count,
        total_capa=capa_count,
        generated_date=datetime.utcnow(),
        created_by=current_user.id
    )
    
    db.add(report)
    db.commit()
    db.refresh(report)
    
    logger.info(f"Monthly report {report_number} generated by {current_user.email}")
    
    return ReportResponse.from_orm(report)
